### PR TITLE
Update License

### PR DESCRIPTION
**Pull request by hobochild**
Not sure why this isn't Apache? It's limited to the website, but good to
have all of resinos things under the same license.

Change-Type: patch

### CODE REVIEW

**Comment by imrehg** [comment]
cc @dfunckt regarding licenses in general?

**Comment by dfunckt** [comment]
@imrehg this repo is only about the site so the license doesn't really affect how resinOS can be used (which is indeed Apache-licensed). I see Craig's point about consistency and I'm +1, though I'm not an expert in licenses nor have any intimate knowledge with regards to how Resin chooses to license projects -- @petrosagg is your man at the moment.

**Comment by lurch** [comment]
I guess it's also not clear from the README that this repo (and hence the license that applies to it) contains just the https://resinos.io/ website?

Kinda funny to note though that it was Craig that initially created the LICENSE file, and also Craig that was later wondering why it wasn't Apache-licensed :wink: (looking at the [commit](https://github.com/resin-os/resinos/commit/cf8df7ba9b5fbfe0fbe9c296037142a6430ef532) where the license was first created, it looks like maybe the website was generated from some kind of boilerplate system, and maybe this boilerplate system just happened to default to using CC0?)

**Comment by imrehg** [comment]
Ping @petrosagg @alexandrosm re: Licence update for the resinOS repo, to sign off on or kill this PR.

**Comment by LucianBuzzo** [comment]
Repin @petrosagg @alexandrosm WRT the license on this repo

**Comment by imrehg** [comment]
@agherzan @jviotti anything happened with this yet?

**Pull request merged**
