### PR TITLE
add link to resin-device-toolbox

### PR DESCRIPTION
**Pull request by imrehg**
Link to the module on npm.

### CODE REVIEW

**Comment by craig-mulligan** [comment]
We changing to a GitHub link right?

**Comment by imrehg** [comment]
@craig-mulligan I think the suggestion after all was linking to the doc. Then it does not need analytics like this, just linking to https://resinos.io/docs/architecture/#resin-device-toolbox
Thoughts?

**Comment by craig-mulligan** [comment]
Yea that sounds fine.

**Comment by imrehg** [comment]
@craig-mulligan updated

**Comment by craig-mulligan** [comment]
👍

**Pull request merged**
