### PR TITLE
devices: Add Balena Fin

### PR DESCRIPTION
**Pull request by thgreasi**
Generated the images from the svg icon that we have in the dashboard.
image

Connects-to: #486
Change-type: minor
Signed-off-by: Thodoris Greasidis <thodoris@resin.io>
---- Autogenerated Waffleboard Connection: Connects to #486

### CODE REVIEW

**Comment by lurch** [comment]
Out of curiosity, what makes a Fin image different from a RPi3 image? Different drivers included / enabled?

**Comment by thgreasi** [comment]
I don't really know, @floion / @agherzan any insights on this?

**Comment by thgreasi** [comment]
@zwalchuk yea sure, even though we will need to have proper docs for the process and I've opened #487 for that.

**Comment by floion** [comment]
@lurch Balena Fin needs a custom dt-blob.bin and one overlay. These are needed for video out, video in and WiFi to function correctly

**Pull request merged**
